name: Java-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:                    #telling it that build or deploy job
    name: my-spc            #name: our wish
    runs-on: self-hosted


    steps:
      - name: Git_checkout
        uses: actions/checkout@v4

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.organization = naveen-jampala \
          -Dsonar.host.url = $SONAR_HOST_URL \
          -Dsonar.token = $SONAR_TOKEN